before_install:
  - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y
install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake -y
  #- sudo apt-get install ubuntu-sdk -y
script:
  - mkdir ../bmicalc-build
  - cd ../bmicalc-build
  - cmake ../bmicalc
  - make
  - make DESTDIR=../bmicalc-build/.ubuntu-sdk-deploy install
  - click build ../bmicalc-build/.ubuntu-sdk-deploy
  - click-review *.click
